[Desktop Entry]
Name=AuroraMint
Type=X-GNOME-Metatheme
Comment=Aurora with default Mint colors
Encoding=UTF-8

[X-GNOME-Metatheme]
GtkTheme=AuroraMint
MetacityTheme=Gilouche
IconTheme=Felicia
GtkColorScheme=fg_color:#000000000000,bg_color:#f6f6f6f6f6f6,text_color:#000000000000,base_color:#ffffffffffff,selected_fg_color:#ffffffffffff,selected_bg_color:#6d6d8c8caaaa,tooltip_fg_color:#000000000000,tooltip_bg_color:#000000000000
